name: Sync Tag with JS Version

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Crucial: Allows the bot to create tags/releases
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Version from JS
        id: get_version
        run: |
          # Finds "vX.X.X" inside your specific file
          # Replace 'schedule-state-card.js' with your actual filename
          VERSION=$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' schedule-state-card.js | head -n 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Found version: $VERSION"

      - name: Check if Tag exists
        id: check_tag
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "EXISTS=true" >> $GITHUB_ENV
            echo "Tag $VERSION already exists. Skipping."
          else
            echo "EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        if: env.EXISTS == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true