name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    uses: ./.github/workflows/auto-tag.yml
    permissions:
      contents: write

  release:
    needs: tag
    if: needs.tag.outputs.created == 'true'
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      tag: ${{ needs.tag.outputs.tag }}
      version: ${{ needs.tag.outputs.version }}
